# ◈ metadata/layout.conf
#
# Required for this repo to function as a valid Gentoo ebuild overlay
# (repos.conf sync-type=git overlays need this to exist and be correct).

masters = gentoo
thin-manifests = true
sign-manifests = false
