#!/usr/bin/env python3
"""
◈ generate-packages-index.py

Portage already auto-maintains a `Packages` index inside PKGDIR whenever you
build with --buildpkg — that's the file this script starts from. Our job is
just to rewrite each entry so it carries an absolute URI pointing at the
GitHub Release asset the package was actually uploaded to, since the blob no
longer lives at the relative CPV path once it's off in a Release.

Portage's binhost fetcher understands a per-entry `URI:` field and will use
it in preference to the relative path when present — this is the same
mechanism the official Gentoo mirrors use to serve packages from arbitrary
CDN locations.

Input:
    PKGDIR/Packages                  - auto-generated by `emerge --buildpkg`
    upload-map.json                  - {relative_path: release_asset_url}
                                        produced by upload-release.py

Output:
    Packages                         - rewritten index, ready to publish
                                        (e.g. to a gh-pages branch)

Usage:
    python3 generate-packages-index.py PKGDIR/Packages upload-map.json Packages
"""
import sys
from pathlib import Path
import json


def parse_packages_file(text: str):
    """Portage's Packages format: a header block, blank line, then one
    stanza per package, each stanza is `Field: value` lines separated by
    blank lines. We keep it as a list of (header_lines, [stanza_dicts])."""
    blocks = text.split("\n\n")
    header = blocks[0]
    stanzas = []
    for block in blocks[1:]:
        block = block.strip("\n")
        if not block:
            continue
        fields = {}
        order = []
        for line in block.splitlines():
            if ":" not in line:
                continue
            key, _, value = line.partition(":")
            key = key.strip()
            fields[key] = value.strip()
            order.append(key)
        stanzas.append((order, fields))
    return header, stanzas


def render_packages_file(header: str, stanzas) -> str:
    out = [header.rstrip("\n"), ""]
    for order, fields in stanzas:
        for key in order:
            out.append(f"{key}: {fields[key]}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} PKGDIR/Packages upload-map.json OUTPUT", file=sys.stderr)
        sys.exit(2)

    packages_path = Path(sys.argv[1])
    upload_map_path = Path(sys.argv[2])
    output_path = Path(sys.argv[3])

    header, stanzas = parse_packages_file(packages_path.read_text())
    upload_map = json.loads(upload_map_path.read_text())

    rewritten = 0
    missing = []
    for order, fields in stanzas:
        cpv = fields.get("CPV") or fields.get("PATH", "").rsplit(".", 1)[0]
        rel_path = fields.get("PATH")
        if rel_path in upload_map:
            fields["URI"] = upload_map[rel_path]
            if "URI" not in order:
                order.append("URI")
            rewritten += 1
        else:
            missing.append(rel_path or cpv or "<unknown>")

    output_path.write_text(render_packages_file(header, stanzas))

    print(f"[info] rewrote {rewritten}/{len(stanzas)} entries with absolute URIs")
    if missing:
        print(f"[warn] {len(missing)} entries had no matching upload (left as relative path):", file=sys.stderr)
        for m in missing:
            print(f"       - {m}", file=sys.stderr)


if __name__ == "__main__":
    main()
